# 配置文件

# 服务端配置
server:
  # 端口设置
  port: 8888

spring:
  # 配置应用信息
  application:
    # 应用名
    name: wcferry-mvn
  # swagger适配
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 本服务参数
wcferry:
  # DLL文件位置
  dll-path: D:\wechatferry\WeChatFerry\clients\java\wcferry-mvn\dll\sdk.dll
  # socket host
  socket-host: 127.0.0.1
  # socket port
  socket-port: 10086
  # 消息队列最大长度
  message-queue-size: 100
